// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: zone.proto

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyClient interface {
	TCP(ctx context.Context, opts ...grpc.CallOption) (Proxy_TCPClient, error)
	UDP(ctx context.Context, opts ...grpc.CallOption) (Proxy_UDPClient, error)
	IDs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*IDsResponse, error)
}

type proxyClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyClient(cc grpc.ClientConnInterface) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) TCP(ctx context.Context, opts ...grpc.CallOption) (Proxy_TCPClient, error) {
	stream, err := c.cc.NewStream(ctx, &Proxy_ServiceDesc.Streams[0], "/Proxy/TCP", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyTCPClient{stream}
	return x, nil
}

type Proxy_TCPClient interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type proxyTCPClient struct {
	grpc.ClientStream
}

func (x *proxyTCPClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *proxyTCPClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *proxyClient) UDP(ctx context.Context, opts ...grpc.CallOption) (Proxy_UDPClient, error) {
	stream, err := c.cc.NewStream(ctx, &Proxy_ServiceDesc.Streams[1], "/Proxy/UDP", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyUDPClient{stream}
	return x, nil
}

type Proxy_UDPClient interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ClientStream
}

type proxyUDPClient struct {
	grpc.ClientStream
}

func (x *proxyUDPClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *proxyUDPClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *proxyClient) IDs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*IDsResponse, error) {
	out := new(IDsResponse)
	err := c.cc.Invoke(ctx, "/Proxy/IDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
// All implementations must embed UnimplementedProxyServer
// for forward compatibility
type ProxyServer interface {
	TCP(Proxy_TCPServer) error
	UDP(Proxy_UDPServer) error
	IDs(context.Context, *empty.Empty) (*IDsResponse, error)
	mustEmbedUnimplementedProxyServer()
}

// UnimplementedProxyServer must be embedded to have forward compatible implementations.
type UnimplementedProxyServer struct {
}

func (UnimplementedProxyServer) TCP(Proxy_TCPServer) error {
	return status.Errorf(codes.Unimplemented, "method TCP not implemented")
}
func (UnimplementedProxyServer) UDP(Proxy_UDPServer) error {
	return status.Errorf(codes.Unimplemented, "method UDP not implemented")
}
func (UnimplementedProxyServer) IDs(context.Context, *empty.Empty) (*IDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IDs not implemented")
}
func (UnimplementedProxyServer) mustEmbedUnimplementedProxyServer() {}

// UnsafeProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServer will
// result in compilation errors.
type UnsafeProxyServer interface {
	mustEmbedUnimplementedProxyServer()
}

func RegisterProxyServer(s grpc.ServiceRegistrar, srv ProxyServer) {
	s.RegisterService(&Proxy_ServiceDesc, srv)
}

func _Proxy_TCP_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).TCP(&proxyTCPServer{stream})
}

type Proxy_TCPServer interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type proxyTCPServer struct {
	grpc.ServerStream
}

func (x *proxyTCPServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *proxyTCPServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Proxy_UDP_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyServer).UDP(&proxyUDPServer{stream})
}

type Proxy_UDPServer interface {
	Send(*Packet) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type proxyUDPServer struct {
	grpc.ServerStream
}

func (x *proxyUDPServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func (x *proxyUDPServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Proxy_IDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).IDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Proxy/IDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).IDs(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Proxy_ServiceDesc is the grpc.ServiceDesc for Proxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Proxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IDs",
			Handler:    _Proxy_IDs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TCP",
			Handler:       _Proxy_TCP_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UDP",
			Handler:       _Proxy_UDP_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "zone.proto",
}
